# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='images_folder/none/no-img.jpg', upload_to='static/image/article'),
        ),
    ]
