# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20160405_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_subject',
            field=models.TextField(max_length=100),
        ),
    ]
