# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160404_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='article_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='article_description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='article_image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='last_updated',
            new_name='article_last_updated',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='article_published',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='subject',
            new_name='article_subject',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='article_tags',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='article_user',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='views',
            new_name='article_views',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='comment_article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='last_updated',
            new_name='comment_last_updated',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='published',
            new_name='comment_published',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='replay',
            new_name='comment_replay',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='comment_id',
            new_name='like_comment',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='like_user',
        ),
    ]
