# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160404_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_user',
            new_name='article_author',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='images_folder/none/no-img.jpg', upload_to='images_folder/users'),
        ),
    ]
