# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
