# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160408_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_comments',
            field=models.IntegerField(default='0'),
        ),
    ]
