# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_article_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='emotion_image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
