# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20160409_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_count',
            field=models.IntegerField(default='0'),
        ),
    ]
